services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: skillsculptor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - docker-symfony-database-data:/var/lib/mysql 
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend/docker/php
      args:
        UID: 1000
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=9005
    volumes:
      - ./backend/:/appdata/www
      - ./backend/docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - app-network
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: ./backend/docker/nginx
      args:
        UID: 1000
    ports:
      - 8080:80
    volumes:
      - ./backend/public:/appdata/www/public
    networks:
      - app-network
    depends_on:
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network

volumes:
  docker-symfony-database-data:

networks:
  app-network:
    driver: bridge